### ISSUE TITLE
Primeira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs#45]
Olá Pessoal!

O Grupo 02 irá avaliar o Grupo 03 nessa primeira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta acessar o Tópico 2 DSW(Base) no Moodle, e procurar por "Primeira Avaliação por Pares".

**Deadline:** 09 de Agosto de 2021, ao final do dia, conforme consta no cronograma.

Atenciosamente.

**Comment by lboaventura25** [comment]
Bom dia, professora!
Muito obrigado pelo aviso, simbora pessoal!!

**Comment by sergiosacj** [comment]
Já concluída!
